### ISSUE TITLE
Makefile does not work with Windows

### ISSUE THREAD

**Issue by kgoodwill** [beeware/batavia#175]
The current Makefile does not support windows. The job 'batavia.js' fails on windows because windows does not support to the 'cat' command.

EDIT: The 'clean' job will also fail and should be fixed in a similar manner.

**Comment by kgoodwill** [comment]
I will work on this issue. I just don't know how to assign it to myself.

**Comment by clach04** [comment]
This issue appears to be resolved (at least I'm not seeing problems under Windows with commit 92085796a690251957dc5f203388b0fdfbe850b1 which is the latest as of today). `type` is being used over `cat` under Windows. There are some instruction issues though (for Windows), I'll post a PR for those.

**Comment by martica** [comment]
Closing this as the Makefile referred to here no longer exists.
