### ISSUE TITLE
Deal with new Python magic number for 3.5.3 and Debian

### ISSUE THREAD

**Issue by shaib** [beeware/batavia#383]
Python bug http://bugs.python.org/issue27286 was resolved by, among other things, bumping the PYC magic number. The patch with the new magic is already included in Debian testing (which calls its Python version "3.5.2+") and will be included in Python 3.5.3.

Ignoring the change causes hundreds (maybe thousands) of test failures. A trivial fix adding the new version constant and treating it as equal to `BATAVIA_MAGIC_35` brings that number down to 17, all of which (except one) seem to be about changed formatting of messages (the one substantial change is in `tests.modules.test_time.TimeTests.test_mktime_too_late` -- newer Python allows year numbers to be four orders of magnitude larger than the test "too big" value).

FWIW, this is the patch:
```
diff --git a/batavia/VirtualMachine.js b/batavia/VirtualMachine.js
index 83cc8e3..0ce22a3 100644
--- a/batavia/VirtualMachine.js
+++ b/batavia/VirtualMachine.js
@@ -1363,6 +1363,7 @@ batavia.VirtualMachine.prototype.byte_BUILD_SET = function(count) {
 batavia.VirtualMachine.prototype.byte_BUILD_MAP = function(size) {
     switch (batavia.BATAVIA_MAGIC) {
         case batavia.BATAVIA_MAGIC_35:
+        case batavia.BATAVIA_MAGIC_35_Debian:
             var items = this.popn(size * 2);
             var dict = new batavia.types.Dict();
 
@@ -1390,6 +1391,7 @@ batavia.VirtualMachine.prototype.byte_BUILD_MAP = function(size) {
 batavia.VirtualMachine.prototype.byte_STORE_MAP = function() {
     switch (batavia.BATAVIA_MAGIC) {
         case batavia.BATAVIA_MAGIC_35:
+        case batavia.BATAVIA_MAGIC_35_Debian:
             throw new batavia.builtins.BataviaError(
                 "STORE_MAP is unsupported with BATAVIA_MAGIC"
             );
diff --git a/batavia/batavia.js b/batavia/batavia.js
index af7d267..19578e1 100644
--- a/batavia/batavia.js
+++ b/batavia/batavia.js
@@ -16,4 +16,5 @@ var batavia = {
 batavia.BATAVIA_MAGIC = null;
 batavia.BATAVIA_MAGIC_34 = String.fromCharCode(238, 12, 13, 10);
 batavia.BATAVIA_MAGIC_35 = String.fromCharCode(22, 13, 13, 10);
+batavia.BATAVIA_MAGIC_35_Debian = String.fromCharCode(23, 13, 13, 10);
 batavia.BATAVIA_MAGIC_35a0 = String.fromCharCode(248, 12, 13, 10);
```

**Comment by freakboy3742** [comment]
ACK. This is the risk of dealing with bytecode.

I'd rather the constant be `BATAVIA_MAGIC_352` rather than call out Debian specifically; if this is going to affect 3.5.2 users as soon as that is released, then it's better to be ahead of the curve.

As for the message text changes: we have some code in the test utils to normalize test messages, but we probably need a broader policy on how we're going to deal with this sort of change, because it's going to keep happening.

**Comment by shaib** [comment]
Yes, we should be using a version number and not "Debian", altough it's 3.5.3: The file in 3.5.2 -- https://hg.python.org/cpython/file/v3.5.2/PC/launcher.c#l1070 -- has 3350 listed as the high limit for 3.5.x magic numbers; that's the `22, 13,` of `BATAVIA_MAGIC_35`. The current 3.5.x source -- https://hg.python.org/cpython/file/3.5/PC/launcher.c#l1070 -- updates that to 3351, corresponding to `23, 13` (it's 0x0D17).

And for the record, no, dealing with bytecode shouldn't have caused this; Python, essentially, broke its stability promises with this change, and it's [acknowledged](http://bugs.python.org/issue27286#msg278158) on the bug.

**Comment by martica** [comment]
The test breakages from this have all been resolved now. The original issue of the new bytecode magic number is resolved. This looks fix. Thanks @shaib.
