### ISSUE TITLE
Babel-preset-latest deprecation warning

### ISSUE THREAD

**Issue by kartikadur** [beeware/batavia#510]
Hi,

During the step to install webpack and other JS dependencies I got a console message: 
>` 'babel-preset-latest' accomplishes the same task as 'babel-preset-env'. Please install it with npm install babel-preset-env --save-dev.`

I assume this was a warning as it was displayed as white font (and not red as is done with errors). I checked the babel website and it mentions that `presets = ["latest"]` is deprecated, and that `presets = ["env"]` should be used instead. 

The only place I'd have to make that change is in 'package.json' since 'webpack.config.js' does not mention babel-latest or babel-env. Since this will be my first edit to the 'Batavia' code, and I am unsure how dependencies w.r.t babel are setup. I was wondering if I would be allowed to make this change. Let me know if there is something I should know before making any changes.

Thanks

**Comment by freakboy3742** [comment]
In short - any change is allowed, as long as the test suite keeps working, and you can make the case for why the change is needed. Sometimes - like this time - it's easy to make the case: there's an error message, and there shouldn't be :-)

I had seen the error, but I hadn't started investigating whether the proposed fix will work. If you make this change, the test suite still passes, and you can't notice any problems that the test suite won't catch, then by all means submit a pull request.

**Comment by kartikadur** [comment]
Thanks, I will get right on it.

**Comment by martica** [comment]
Looks like this is resolved. package.json current includes babel/preset-env.
