### ISSUE TITLE
[BUG] Raising exception inside for loop

### ISSUE THREAD

**Issue by abonie** [beeware/batavia#574]
I stumbled upon a bug. Run in testbed, this code:
```python
for x in ['a', 'b']:  # same for ['a']
    try:
        raise Exception()
    except:
    	print(x)
```
results in:
```
a
Traceback (most recent call last):
  File "/tmp/tmp9y1iik0h", line 1, in <module>
TypeError: TypeError: iterobj is undefined
```
which clearly is not what should happen.
I don't have time atm to try and deal with this, it is not blocking me, but I think it is an important use case, so I am just putting it out there. Up for grabs.

**Comment by agronauts** [comment]
I'll have a go at this!

**Comment by agronauts** [comment]
What branch is this on? I am on the latest master branch and get this output instead:
```
a
Traceback (most recent call last):
  File "/tmp/tmpts8ew0y2", line 1, in <module>
TypeError: TypeError: Cannot read property '__next__' of undefined
```

**Comment by abonie** [comment]
I just retried and got same error as before.
Pulled from upstream master, ran `npm run build` with Python 3.4.6, node v6.9.1

**Comment by agronauts** [comment]
[issue574_notes.txt](https://github.com/pybee/batavia/files/1236895/issue574_notes.txt)
Finding this a very difficult thing to debug if someone else wants to get it a go. Attached are my notes on it

**Comment by martica** [comment]
I can't reproduce this now. Looks like it got fixed along the way. I've added your repro as a test case to ensure it stays that way. Thanks!
