### ISSUE TITLE
PyStone seems to be going into an infinite loop

### ISSUE THREAD

**Issue by timb07** [beeware/batavia#602]
Using the Batavia testbed, clicking "Run PyStone (5 loops)" seems to go into an infinite loop: the browser process uses 100% CPU, and the browser tab becomes unresponsive.

**Comment by timb07** [comment]
Copying and pasting the PyStone code from `test_pystone.py` into the testbed and running it directly (with `main(1)`) works fine.

**Comment by davem7** [comment]
I was just going through the tutorial and thought I was having the same issue, but after letting it sit for a bit, the Console output showed the results for 50000 loops.  It seems to execute 50000 loops regardless of which button is pressed.

**Comment by martica** [comment]
It looks like the issue you found (List.__len__ returning a JS int) @timb07 is resolved now. Thanks for the report and the investigation.
