### ISSUE TITLE
'./manage.py runserver' fails [Window]

### ISSUE THREAD

**Issue by JaesungNa** [beeware/batavia#690]
In README.rst, [Running Batavia in the browser](https://github.com/pybee/batavia#running-batavia-in-the-browser) section,

It guides us to write './manage.py runserver' command to run the server without the indication of appropriate OS, which however clearly indicated in [Python In The Browser](http://batavia.readthedocs.io/en/latest/tutorial/tutorial-1.html).

If we could state whether this command works in Mac or Window, it could be more clear.
-for Window : 'py manage.py runserver'

Any suggestion?

**Comment by smitar0y** [comment]
Do you want to change the write up in Running Batavia in the browser section?

**Comment by freakboy3742** [comment]
Any clarification for Windows users is definitely appreciated.

**Comment by kosiew** [comment]
On Windows, when I ran 
(beeware) c:\beeware\batavia\testserver>python manage.py runserver

  File "c:\beeware\batavia\testserver\urls.py", line 8, in <module>
    from test import pystone
ImportError: cannot import name 'pystone'

**Comment by martica** [comment]
Looks like the current state of the README shows the proper command for Windows.
