### ISSUE TITLE
Error in Batavia/builtins/round.js

### ISSUE THREAD

**Issue by examin** [beeware/batavia#721]
## Expected Behavior
The built-in Python function round() takes in two numbers, one to be rounded, and one that specifies the number of decimal places to include.
## Current Behavior
producing some unexpected error

## Steps to reproduce

1.

![batavia testbed localhost_8000](https://user-images.githubusercontent.com/18100892/37089066-613405de-2225-11e8-8eb6-90780e072b50.png)

## Your Environment

* Python Version 3.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [#] Windows
  - [ ] Ubuntu

**Comment by martica** [comment]
This is fixed at head now. Thanks for the report!
