### ISSUE TITLE
For loops with sequence objects

### ISSUE THREAD

**Issue by SebStreb** [beeware/batavia#762]
I was trying to use for loops with iterable objects (implementing __iter__ method or __len__ and __getitem__ methods). I discovered that currently batavia does not accept objects implementing the sequence protocol (__len__ and __getitem__ methods).

The following code works on normal python but not on batavia :

```
class Test:
    def __init__(self, l):
        self.l = l
    def __len__(self):
        return len(self.l)
    def __getitem__(self, index):
        return self.l[index]
t = Test([1 ,2, 3, 6])

total = 0
for i in t:
    total = total + i
    print(i, total)
print('Done.')
```

I'm using python3.5 in a virtual environment running on macOS 10.14.1.

**Comment by martica** [comment]
Thanks for the report and the fix!
