### ISSUE TITLE
RefreenceError: CodeMirror not defined

### ISSUE THREAD

**Issue by ashneg** [beeware/batavia#801]
![Screenshot (25)](https://user-images.githubusercontent.com/44631967/58561758-7e9bba00-8245-11e9-8ff4-328d2492ce7e.png)
## Expected Behavior
the output should be displayed for the respective python code

## Current Behavior
Value error is being displayed (Most probably due to ReferenceError)

## Steps to reproduce

1. git clone Batavia and follow the setup steps here:
    https://github.com/beeware/batavia

2. Running the test server using:
    python manage.py runserver

Also tried installing codemirror separately from npm and then binding it, but it doesn't work

## Your Environment

* Python Version (3.7.2)

* npm Version (5.6.0)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [x] Windows 10
  - [ ] Ubuntu

**Comment by martica** [comment]
The codemirror error is spurious as far as I understand it. The real issue here is that we don't yet support python 3.7. If you try with python 3.4 through 3.6, you should be in much better shape.

**Comment by ashneg** [comment]
Thanks , it worked on python 3.5
