### ISSUE TITLE
Convert Pandas to Javascript?

### ISSUE THREAD

**Issue by abalter** [beeware/batavia#821]
If I compiled the entire Pandas library (or scipy, statsmodels, numpy, etc.) down to bytecode, would it run in Batavia? Could I then call it directly with JS?

**Comment by freakboy3742** [comment]
@abalter Unfortunately, it's not *quite* that simple. Numerical processing libraries (like scipy and numpy) contain some Python code, but the core of the logic is implemented in C. Batavia is a pure Bytecode machine - it can't do anything with C code.

If you're interested in running NumPy etc in the browser, you may want to look into [Pyodide](https://alpha.iodide.io/notebooks/300/). Pyodide uses WASM to compile both the Python interpreter *and* the C module code into web assembly, which means it can run in the browser.

**Comment by abalter** [comment]
@freakboy3742  Makes sense. I sort of knew that, but I wasn't sure if the core still somehow ended up running on the python virtual machine.
